# Generated by Django 3.2.5 on 2021-08-29 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0002_delete_testonetoonestartmodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testbroker",
            options={"permissions": [("unique_permission", "Unique permission")]},
        ),
    ]
