# Generated by Django 3.2.5 on 2021-08-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0004_auto_20210829_1154"),
    ]

    operations = [
        migrations.CreateModel(
            name="DummyModel",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
            ],
        ),
    ]
