name: Coverage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.6
    - name: Run coverage check
      run: |
        python -m pip install --upgrade pip
        pip install -r ./dev_requirements.txt
        python setup.py install
        cd tests/test_project
        path="$(which python)"
        toReplace="bin/python"
        newValue="lib/python3.8/site-packages/smart_security/"
        package=${path/$toReplace/$newValue}
        coverage run --source="$package" manage.py test
        coverage report --fail-under=100