name: Flake8

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./dev_requirements.txt
    - name: Analysing the code with flake8
      run: flake8
