name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.14
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.11
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.6
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.6
    - name: Install tox
      run: pip install tox
    - name: Run tests
      run: tox --recreate
