name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.6
    - name: Run tests
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
        python setup.py install
        cd tests/test_project
        python manage.py test
